### ISSUE TITLE
How to log in?

### ISSUE THREAD

**Issue by y-vas** [minhng92/odoo-15-docker-compose#1]
I cloned the project started everything with docker ...

But i'm stuck on the login part.
I tried with 'odoo15@2021', 'postgress' ... and all the posible combinations with the inforamtion that i could find...
But i always get an Access denied response.

I have to log in with a specific user name?

**Comment by minhng92** [comment]
Hi @y-vas ,

If you create a new database, you have to fill in user name and password of the admin user. Password to create a new database is stored in _etc/odoo.conf_ (currently set **minhng.info** in my repository).

If you don't see any form to create a new Odoo database, the default login will be:
- Username: **admin**
- Password: **admin**

**Comment by y-vas** [comment]
I got confused with **Master Password**. Thank you.
